"""first migrate

Revision ID: 8ef6a4c44edb
Revises: 23f18fe04c9e
Create Date: 2024-05-16 15:45:48.717550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef6a4c44edb'
down_revision = '23f18fe04c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_burnable_sum', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('non_burnable_sum')

    # ### end Alembic commands ###
