"""Added hints to the user

Revision ID: e4f792f27f80
Revises: 8ef6a4c44edb
Create Date: 2024-05-16 16:29:56.234933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f792f27f80'
down_revision = '8ef6a4c44edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hints', sa.PickleType(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hints')

    # ### end Alembic commands ###
